### ISSUE TITLE
CREO2URDF – Beta Testing – iRonCub team

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/creo2urdf#50]
Cool, thanks a lot to everyone!

> Beta testing. We need to identify a bunch of testers.

To suggest someone: iRonCub mech team has been historically a long time user of simmechanics-to-urdf, I guess they may be interested in trying creo2urdf, probably we can ask to Gabriele Nava.

_Originally posted by @traversaro in https://github.com/icub-tech-iit/creo2urdf/issues/1#issuecomment-1702824644_

**Comment by Nicogene** [comment]
We had today a meeting with the iRonCub team and we agreed that they will give it a try to obtain the urdf of iRonCub after the ICRA deadline (15th September).
In order to ease the setup we will provide directly the dll.
From this meeting, came out the necessity of building automation for running creo2urdf automatically after every change in the YAML files, we will investigate in the near future the possibility of running creo headless.
Closing.
